filter:
  paths: [src/*]
  excluded_paths: [vendor/*, test/*]
before_commands:
  - 'composer install --dev --prefer-source'

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          -
            command: ./vendor/bin/phpunit
            coverage:
                file: build/coverage.xml
                format: clover
  environment:
    postgresql: false
    mysql: false
    redis: false
    php:
      version: 7.2
  
